apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push
spec:
  params:
    - name: IMAGE
      type: string
      description: Docker registry image 
      default: kyesikov/radio:latest
    - name: DOCKERFILE
      type: string
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      type: string
      description: The build context used by Kaniko.
      default: ./
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.6.0
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --destination=$(params.IMAGE)
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --oci-layout-path=$(workspaces.source.path)/image-digest
        - --insecure
        - --skip-tls-verify
      securityContext:
        runAsUser: 0
  workspaces:
    - name: source
