apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: "demo.pipeline"
spec:
  params:
  - name: image-registry
    default: gcr.io/christiewilson-catfactory
  workspaces:
  - name: git-source
  tasks:
  - name: fetch-from-git
    taskRef:
      name: git-clone
    params:
    - name: url
      value: https://github.com/GoogleContainerTools/skaffold
    - name: revision
      value: main
    workspaces:
    - name: output
      workspace: git-source
  - name: build-image
    runAfter: [fetch-from-git]
    taskRef:
      name: kaniko
    params:
    - name: IMAGE
      value: $(params.image-registry)/getting-started
    - name: CONTEXT
      value: examples/getting-started
    - name: DOCKERFILE
      value: $(workspaces.source.path)/examples/getting-started/Dockerfile
    workspaces:
    - name: source
      workspace: git-source

      ---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: demo-pipeline-run-1
spec:
  pipelineRef:
    name: "demo.pipeline"
  taskRunTemplate:
    serviceAccountName: 'default'
  workspaces:
  - name: git-source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
