apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: Kubectl Imperative Deploy
spec:
  params:
    - name: MANIFEST_PATH
      type: string
      description: Path to the manifest to apply
      default: ./deployment.yaml
    - name: YAML_PATH_TO_IMAGE 
      type: string
      description: The path to the image to replace in the yaml manifest (arg to yq)
      default: spec.template.spec.containers[0].image
    - name: IMAGE 
      type: string
      description: The name of the image that was built
    - name: ACTION
      type: string
      description: The action to perform with kubectl
      default: "apply"
  steps:
    - name: replace-image
      image: mikefarah/yq
      workingDir: $(workspaces.source.path)
      script: |
        yq w -i $(params.MANIFEST_PATH) "$(params.YAML_PATH_TO_IMAGE)" $(params.IMAGE) 
    - name: run-kubectl 
      image: lachlanevenson/k8s-kubectl
      workingDir: $(workspaces.source.path)
      script: |
        kubectl $(params.ACTION) -f $(params.MANIFEST_PATH)
  workspaces:
    - name: source
  results:
    - name: IMAGE 
      description: The name of the image that was built
